export const sampleStationDataFromZip = {
  "latitude": 40.775433,
  "longitude": -89.639114,
  "precision": {
    "value": 5,
    "name": "postal_code",
    "types": [
      "postal_code"
    ]
  },
  "station_locator_url": "http://www.afdc.energy.gov/afdc/locator/stations/",
  "total_results": 8,
  "station_counts": {
    "total": 11,
    "fuels": {
      "BD": {
        "total": 0
      },
      "E85": {
        "total": 0
      },
      "ELEC": {
        "total": 9,
        "stations": {
          "total": 6
        }
      },
      "HY": {
        "total": 0
      },
      "LNG": {
        "total": 0
      },
      "CNG": {
        "total": 0
      },
      "LPG": {
        "total": 2
      }
    }
  },
  "offset": 0,
  "fuel_stations": [
    {
      "access_code": "public",
      "access_days_time": "Dealership business hours",
      "access_detail_code": "CALL",
      "cards_accepted": null,
      "date_last_confirmed": "2018-07-09",
      "expected_date": null,
      "fuel_type_code": "ELEC",
      "groups_with_access_code": "Public - Call ahead",
      "id": 47221,
      "open_date": "2012-01-31",
      "owner_type_code": "P",
      "status_code": "E",
      "station_name": "Uftring Nissan",
      "station_phone": "309-690-6200",
      "updated_at": "2018-07-09T12:13:28Z",
      "geocode_status": "200-9",
      "latitude": 40.777601,
      "longitude": -89.630469,
      "city": "Peoria",
      "intersection_directions": null,
      "plus4": null,
      "state": "IL",
      "street_address": "7400 N Allen Rd",
      "zip": "61614",
      "country": "US",
      "bd_blends": null,
      "e85_blender_pump": null,
      "ev_connector_types": [
        "J1772"
      ],
      "ev_dc_fast_num": null,
      "ev_level1_evse_num": null,
      "ev_level2_evse_num": 1,
      "ev_network": null,
      "ev_network_web": null,
      "ev_other_evse": null,
      "hy_is_retail": null,
      "hy_status_link": null,
      "lpg_primary": null,
      "ng_fill_type_code": null,
      "ng_psi": null,
      "ng_vehicle_class": null,
      "distance": 0.47752,
      "distance_km": 0.76849
    },
    {
      "access_code": "private",
      "access_days_time": null,
      "access_detail_code": null,
      "cards_accepted": null,
      "date_last_confirmed": "2018-07-09",
      "expected_date": null,
      "fuel_type_code": "ELEC",
      "groups_with_access_code": "Private",
      "id": 47222,
      "open_date": "2012-01-31",
      "owner_type_code": "P",
      "status_code": "E",
      "station_name": "Uftring Nissan",
      "station_phone": "309-690-6200",
      "updated_at": "2018-07-09T12:13:28Z",
      "geocode_status": "200-9",
      "latitude": 40.777601,
      "longitude": -89.630469,
      "city": "Peoria",
      "intersection_directions": null,
      "plus4": null,
      "state": "IL",
      "street_address": "7400 N Allen Rd",
      "zip": "61614",
      "country": "US",
      "bd_blends": null,
      "e85_blender_pump": null,
      "ev_connector_types": [
        "J1772"
      ],
      "ev_dc_fast_num": null,
      "ev_level1_evse_num": null,
      "ev_level2_evse_num": 1,
      "ev_network": null,
      "ev_network_web": null,
      "ev_other_evse": null,
      "hy_is_retail": null,
      "hy_status_link": null,
      "lpg_primary": null,
      "ng_fill_type_code": null,
      "ng_psi": null,
      "ng_vehicle_class": null,
      "distance": 0.47752,
      "distance_km": 0.76849
    },
    {
      "access_code": "public",
      "access_days_time": "Dealership business hours; Mitsubishi vehicle use only",
      "access_detail_code": null,
      "cards_accepted": null,
      "date_last_confirmed": "2018-01-04",
      "expected_date": null,
      "fuel_type_code": "ELEC",
      "groups_with_access_code": "Public",
      "id": 45803,
      "open_date": "2012-02-15",
      "owner_type_code": "P",
      "status_code": "E",
      "station_name": "Mike Miller Mitsubishi",
      "station_phone": "877-273-0662",
      "updated_at": "2018-03-06T01:29:15Z",
      "geocode_status": "200-9",
      "latitude": 40.784164,
      "longitude": -89.623657,
      "city": "Peoria",
      "intersection_directions": null,
      "plus4": null,
      "state": "IL",
      "street_address": "2007 W Pioneer Pkwy",
      "zip": "61615",
      "country": "US",
      "bd_blends": null,
      "e85_blender_pump": null,
      "ev_connector_types": [
        "J1772"
      ],
      "ev_dc_fast_num": null,
      "ev_level1_evse_num": null,
      "ev_level2_evse_num": 1,
      "ev_network": null,
      "ev_network_web": null,
      "ev_other_evse": null,
      "hy_is_retail": null,
      "hy_status_link": null,
      "lpg_primary": null,
      "ng_fill_type_code": null,
      "ng_psi": null,
      "ng_vehicle_class": null,
      "distance": 1.0101,
      "distance_km": 1.6256
    },
    {
      "access_code": "public",
      "access_days_time": "6:30am-10pm M-Sat, 8am-8pm Sun",
      "access_detail_code": null,
      "cards_accepted": "A Cash Checks D M V",
      "date_last_confirmed": "2018-01-04",
      "expected_date": null,
      "fuel_type_code": "LPG",
      "groups_with_access_code": "Public",
      "id": 50507,
      "open_date": "2018-01-02",
      "owner_type_code": "P",
      "status_code": "E",
      "station_name": "Menards",
      "station_phone": "309-693-0416",
      "updated_at": "2018-03-06T01:56:01Z",
      "geocode_status": "200-9",
      "latitude": 40.799221,
      "longitude": -89.63482,
      "city": "Peoria",
      "intersection_directions": null,
      "plus4": null,
      "state": "IL",
      "street_address": "2627 W Townline Rd",
      "zip": "61615",
      "country": "US",
      "bd_blends": null,
      "e85_blender_pump": null,
      "ev_connector_types": null,
      "ev_dc_fast_num": null,
      "ev_level1_evse_num": null,
      "ev_level2_evse_num": null,
      "ev_network": null,
      "ev_network_web": null,
      "ev_other_evse": null,
      "hy_is_retail": null,
      "hy_status_link": null,
      "lpg_primary": true,
      "ng_fill_type_code": null,
      "ng_psi": null,
      "ng_vehicle_class": null,
      "distance": 1.65682,
      "distance_km": 2.66639
    },
    {
      "access_code": "public",
      "access_days_time": "24 hours daily",
      "access_detail_code": null,
      "cards_accepted": null,
      "date_last_confirmed": "2018-07-22",
      "expected_date": null,
      "fuel_type_code": "ELEC",
      "groups_with_access_code": "Public",
      "id": 69693,
      "open_date": null,
      "owner_type_code": null,
      "status_code": "E",
      "station_name": "HY VEE",
      "station_phone": "888-758-4389",
      "updated_at": "2018-07-22T08:47:05Z",
      "geocode_status": "GPS",
      "latitude": 40.7802106,
      "longitude": -89.6779853,
      "city": "Peoria",
      "intersection_directions": "PEORIA #2B; East side of parking lot next to light pole",
      "plus4": null,
      "state": "IL",
      "street_address": "7611 North Grand Prairie Drive",
      "zip": "61615",
      "country": "US",
      "bd_blends": null,
      "e85_blender_pump": null,
      "ev_connector_types": [
        "J1772"
      ],
      "ev_dc_fast_num": null,
      "ev_level1_evse_num": null,
      "ev_level2_evse_num": 2,
      "ev_network": "ChargePoint Network",
      "ev_network_web": "http://www.chargepoint.com/",
      "ev_other_evse": null,
      "hy_is_retail": null,
      "hy_status_link": null,
      "lpg_primary": null,
      "ng_fill_type_code": null,
      "ng_psi": null,
      "ng_vehicle_class": null,
      "ev_network_ids": {
        "posts": [
          "1:115985"
        ]
      },
      "distance": 2.06545,
      "distance_km": 3.32402
    },
    {
      "access_code": "public",
      "access_days_time": "24 hours daily",
      "access_detail_code": null,
      "cards_accepted": null,
      "date_last_confirmed": "2018-07-22",
      "expected_date": null,
      "fuel_type_code": "ELEC",
      "groups_with_access_code": "Public",
      "id": 69691,
      "open_date": null,
      "owner_type_code": null,
      "status_code": "E",
      "station_name": "HY VEE",
      "station_phone": "888-758-4389",
      "updated_at": "2018-07-22T08:47:05Z",
      "geocode_status": "GPS",
      "latitude": 40.7801334,
      "longitude": -89.6788061,
      "city": "Peoria",
      "intersection_directions": "PEORIA#2A; West side of main lot next to light pole",
      "plus4": null,
      "state": "IL",
      "street_address": "7400 N Orange Prairie Rd",
      "zip": "61615",
      "country": "US",
      "bd_blends": null,
      "e85_blender_pump": null,
      "ev_connector_types": [
        "J1772"
      ],
      "ev_dc_fast_num": null,
      "ev_level1_evse_num": null,
      "ev_level2_evse_num": 2,
      "ev_network": "ChargePoint Network",
      "ev_network_web": "http://www.chargepoint.com/",
      "ev_other_evse": null,
      "hy_is_retail": null,
      "hy_status_link": null,
      "lpg_primary": null,
      "ng_fill_type_code": null,
      "ng_psi": null,
      "ng_vehicle_class": null,
      "ev_network_ids": {
        "posts": [
          "1:113589"
        ]
      },
      "distance": 2.10714,
      "distance_km": 3.39111
    },
    {
      "access_code": "public",
      "access_days_time": "24 hours daily",
      "access_detail_code": null,
      "cards_accepted": null,
      "date_last_confirmed": "2018-07-22",
      "expected_date": null,
      "fuel_type_code": "ELEC",
      "groups_with_access_code": "Public",
      "id": 79424,
      "open_date": null,
      "owner_type_code": null,
      "status_code": "E",
      "station_name": "KNOXVILLE CROSS",
      "station_phone": "888-758-4389",
      "updated_at": "2018-07-22T08:47:05Z",
      "geocode_status": "GPS",
      "latitude": 40.8146846,
      "longitude": -89.6146864,
      "city": "Peoria",
      "intersection_directions": "SCHNUCK PEORIA",
      "plus4": null,
      "state": "IL",
      "street_address": "North Centerway Drive",
      "zip": "61615",
      "country": "US",
      "bd_blends": null,
      "e85_blender_pump": null,
      "ev_connector_types": [
        "J1772"
      ],
      "ev_dc_fast_num": null,
      "ev_level1_evse_num": null,
      "ev_level2_evse_num": 2,
      "ev_network": "ChargePoint Network",
      "ev_network_web": "http://www.chargepoint.com/",
      "ev_other_evse": null,
      "hy_is_retail": null,
      "hy_status_link": null,
      "lpg_primary": null,
      "ng_fill_type_code": null,
      "ng_psi": null,
      "ng_vehicle_class": null,
      "ev_network_ids": {
        "posts": [
          "1:159921"
        ]
      },
      "distance": 2.99614,
      "distance_km": 4.82182
    },
    {
      "access_code": "public",
      "access_days_time": "7am-7pm M-Th and Sat, 7am-8pm F, 9am-5pm Sun",
      "access_detail_code": null,
      "cards_accepted": "A Cash D M V",
      "date_last_confirmed": "2017-11-02",
      "expected_date": null,
      "fuel_type_code": "LPG",
      "groups_with_access_code": "Public",
      "id": 70907,
      "open_date": null,
      "owner_type_code": "P",
      "status_code": "E",
      "station_name": "U-Haul",
      "station_phone": "309-682-3213",
      "updated_at": "2018-03-06T00:01:01Z",
      "geocode_status": "200-9",
      "latitude": 40.731168,
      "longitude": -89.615106,
      "city": "Peoria",
      "intersection_directions": null,
      "plus4": null,
      "state": "IL",
      "street_address": "3650 N Meadowbrook Rd",
      "zip": "61604",
      "country": "US",
      "bd_blends": null,
      "e85_blender_pump": null,
      "ev_connector_types": null,
      "ev_dc_fast_num": null,
      "ev_level1_evse_num": null,
      "ev_level2_evse_num": null,
      "ev_network": null,
      "ev_network_web": null,
      "ev_other_evse": null,
      "hy_is_retail": null,
      "hy_status_link": null,
      "lpg_primary": true,
      "ng_fill_type_code": null,
      "ng_psi": null,
      "ng_vehicle_class": null,
      "distance": 3.30401,
      "distance_km": 5.31729
    }
  ]
};